# Generated by Django 3.1.6 on 2021-02-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=50)),
                ('application_link', models.URLField()),
                ('scan_type', models.CharField(choices=[('light_scan', 'Light Scan'), ('full_scan', 'Full Scan')], default='light_scan', max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scan reports',
                'ordering': ('-application_name',),
            },
        ),
    ]
