# Generated by Django 3.1.6 on 2021-02-12 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-scan_date',)},
        ),
        migrations.RenameField(
            model_name='report',
            old_name='publish',
            new_name='scan_date',
        ),
    ]
