# Generated by Django 3.1.6 on 2021-02-12 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_name', models.CharField(max_length=50)),
                ('application_link', models.URLField()),
                ('scan_type', models.CharField(choices=[('light_scan', 'Light Scan'), ('full_scan', 'Full Scan')], default='light_scan', max_length=30)),
                ('scan_status', models.CharField(choices=[('not_initiated', 'Not initiated'), ('scheduled', 'Scheduled'), ('scanning', 'Scanning'), ('completed', 'Completed')], default='not_initiated', max_length=30)),
                ('scan_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('scanned_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scan reports',
                'ordering': ('-scan_date',),
            },
        ),
    ]
